### ISSUE TITLE
Travis CI exploitation

### ISSUE THREAD

**Issue by szaghi** [pdebuyl/fortran_tester#8]
Dear @pdebuyl 

In the last years I have found that Travis CI is a great help for us. I do not know if you are aware about it, but in very few words it help us to automate many boring stuff like automatic build/test/coverage-analysis/doc-deploy...

I have configured my fork of _fortran_tester_ to exploit Travis CI, e.g. [see the last log](https://travis-ci.org/szaghi/fortran_tester#L366).

The Travis CI exploitation is more than add a config file (hidden) file to your project, the following mine (just as a skeleton for you):

``` yaml
language: generic

sudo: false

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - binutils
      - python-pip
      - graphviz

env:
  global:
    - MAKECOVERAGE="./scripts/makecoverage.sh"
    - MAKEDOC=""
    - CLEAN=""
    - MAKETAR=""

before_install:
  - git submodule update --init --recursive

install:
  - |
    if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir "$HOME/.local/bin"
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - export FC=/usr/bin/gfortran-6
  - ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran" && gfortran --version
  - ls -l /usr/bin/gfortran-6
  - ln -fs /usr/bin/gcov-6 "$HOME/.local/bin/gcov" && gcov --version
  # - pip install --user --upgrade pygooglechart
  # - pip install --user --upgrade graphviz
  # - pip install --user --upgrade FoBiS.py
  # - pip install --user --upgrade markdown-checklist 
  # - pip install --user --upgrade ford

script:
  - $MAKECOVERAGE

# after_success:
#   - find . -name '*.gcno' -print
#   - bash <(curl -s https://codecov.io/bash)
#   - $MAKEDOC

# before_deploy:
#   - $CLEAN
#   - $MAKETAR
#   - mv fortran_tester.tar.gz fortran_tester-$TRAVIS_TAG.tar.gz

# deploy:
#   provider: releases
#   api_key:
#     secure: 
#   file: 
#     - fortran_tester-$TRAVIS_TAG.tar.gz
#     - ./scripts/install.sh
#   skip_cleanup: true
#   overwrite: true
#   on:
#     tags: true
```

Do you think you like such a help?
